### ISSUE TITLE
can not flash offical rom(.ozip)

### ISSUE THREAD

**Issue by yz1311** [PitchBlackRecoveryProject/android_device_realme_RMX2121-pbrp#6]
can not flash offical rom(.ozip)

zip file is corrupt!
Error installing zip file

**Comment by zeng-github01** [comment]
I have submitted a PR of the OZIP decryption key change to this repository, and it should be possible to flash in in the future.

**Comment by zeng-github01** [comment]
Twrp recently updated its ozip support for Android 11. The latest version should be available
